language: node_js

node_js:
  - 11

jobs:
  include:
    - stage: release
      node_js: 11
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
